swagger: "2.0"
info:
  title: "Delilah Resto by Dehnike Ezequiel"
  description: "API para restaurant [http://ejemplo.com](http://ejemplo.com)"
  contact:
    email: "ezequieldehnike@gmail.com"
  version: "1.0.0"
externalDocs:
  description: "Github Repository"
  url: "https://github.com/ezequieldehnike/Delilah_Resto-proyect-3"
tags:
  - name: "Ingreso"
    description: "Ingreso al Sitio"
  - name: "Usuarios"
    description: "Operaciones sobre Usuarios"
  - name: "Productos"
    description: "Operaciones sobre Productos"
  - name: "Pedidos"
    description: "Operaciones sobre Pedidos"
schemes:
- "https"
- "http"
paths:
  /v1/usuarios:
    post:
      tags:
        - "Usuarios"
      summary: "Crear Usuario"
      description: "Crear un usuario en la base de datos"
      operationId: "crearUsuario"
      consumes:
      - "aplication/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Usuario creado"
        required: true
        schema:
          type: "object"
          properties:
            usuario: 
              type: "string"
            nombre:
              type: "string"
            apellido: 
              type: "string"
            email:
              type: "string"
            contrasena: 
              type: "integer"
            telefono:
              type: "integer"
            domicilio:
              type: "integer"
      responses:
        "200":
          description: "Usuario Creado Correctamente"
        "400":
          description: "Error al Crear Usuario"
        "409":
          description: "El Usuario ya existe en la base de Datos"
        "500":
          description : "Error"
          
    get:
      tags:
        - "Usuarios"
      summary: "Muestra el listado de Usuarios"
      description: "Muestra el listado de USuarios, se debe enviar Token"
      operationId: "buscarUsuario"
      consumes:
        - "aplication/json"
      parameters: 
      - in: query
        name: "usuario"
        type: "string"
        required: true
      responses:
        "200":
          description: "Usuario encontrado"
          schema:
            type: "object"
            properties:
              id: 
                type: "string"
              usuario: 
                type: "string"
              nombre:
                type: "string"
              apellido: 
                type: "string"
        "401":
          description: "Token Invalido"
        "404":
          description: "Usuario no Encontrado"
        "500":
          description : "Error"
          
    put:
      tags:
        - "Usuarios"
      summary: "Edita un usuario"
      operationId: "editarUsuario"
      consumes:
        - "aplication/json"
      parameters:
        - in: "body"
          name: "usuario"
          required: true
          schema:
            type: "string"
        - in: query
          name: "usuario"
          type: "string"
        - in: query
          name: "nombre"
          type: "string"
        - in: query
          name: "apellido"
          type: "string"
        - in: query
          name: "email"
          type: "string"  
        - in: query
          name: "contrasena"
          type: "string"
        - in: query
          name: "telefono"
          type: "string"  
        - in: query
          name: "domicilio"
          type: "string"  
      responses:
        "201":
          description: "Usuario actualizado"
          schema:
            type: "object"
            properties:
              usuario: 
                type: "string"
              nombre:
                type: "string"
              apellido: 
                type: "string"
              email:
                type: "string"
              contrasena: 
                type: "integer"
              telefono:
                type: "integer"
              domicilio:
                type: "integer"
        "401":
          description: "Token Invalido"
        "404":
          description: "Usuario no Encontrado"
        "500":
          description : "Error"
          
    delete:
      tags:
        - "Usuarios"
      summary: "Elimina Usuario"
      operationId: "eliminarUsuario"
      parameters: 
      - in: query
        name: "usuario"
        type: "string"
        required: true
      responses:
        "201":
          description: "usuario eliminado"
        "401":
          description: "Token Invalido"
        "404":
          description: "Usuario no Encontrado"
        "500":
          description : "Error"

  /v1/ingreso:
  
    get:
      tags:
        - "Ingreso"
      summary: "Ingreso al Sistema"
      operationId: "loginUsuario"
      parameters:
        - in: query
          name: "usuario"
          description: "El usuario para acceder"
          required: true
          type: "string"
        - in: query
          name: "contraseña"
          description: "La contraseña para acceder" 
          required: true
          type: "string"
      responses:
        "200":
          description: "Login Correcto"
        "400":
          description: "Error en Usuario o Contraseña"
        "500":
          description : "Error"
          
  /v1/productos:
  
    get:
      tags:
        - "Productos"
      summary: "Trae el Listado de Productos"
      description: "Muestra todos los productos"
      operationId: "buscarProducto"
      parameters:
        - in: query 
          name: "busqueda"
          description: "Busqueda por nombre"
          type: "string"
          required: true 
      responses:
        "200":
          description: "Producto encontrado"
          schema:
            type: "object"
            properties:
              nombre: 
                type: "string"
              precio: 
                type: "string"
              imagen:
                type: "string"
              descripcion: 
                type: "string"
        "404":
          description: "Producto no encontrado"
        "500":
          description : "Error"
          
    post:
      tags:
        - "Productos"
      summary: "Agrega Producto"
      description: "Agrega producto al sistema"
      operationId: "crearProducto"
      consumes:
      - "aplication/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Producto creado"
        required: true
        schema:
          type: "object"
          properties:
            nombre: 
              type: "string"
            precio:
              type: "string"
            imagen: 
              type: "string"
            descripcion:
              type: "string"
      responses:
        "200":
          description: "Productos Agregado Correctamente"
        "400":
          description: "Error al agregar Producto"
        "409":
          description: "Producto ya existe en la base de datos"
        "500":
          description : "Error"
          
    put:
      tags:
        - "Productos"
      summary: "Editar un producto"
      operationId: "editarProducto"
      description: "Edita las especificaciones de un producto"
      consumes:
        - "aplication/json"
      parameters:
        - in : "body"
          name: "id"
          description: "El Id del producto"
          required: true
          schema:
            type: "string"
        - in: query
          name: "nombre"
          type: "string"
        - in: query
          name: "precio"
          type: "string"
        - in: query
          name: "imagen"
          type: "string"
        - in: query
          name: "descripcion"
          type: "string"  
      responses:
        "200":
          description: "Producto modificado Correctamente"
          schema:
            type: "object"
            properties:
              nombre: 
                type: "string"
              precio: 
                type: "string"
              imagen:
                type: "string"
              descripcion: 
                type: "integer"
        "400":
          description: "Error al editar producto"
        "401":
          description: "Token Invalido"
        "500":
          description : "Error"
          
    delete:
      tags:
        - "Productos"
      summary: "Elimina un producto"
      description: "Elimina un prodcto mediante el ID"
      operationId: "borrarProducto"
      parameters: 
      - in: query
        name: "usuario"
        description: "El Id del producto es necesario para eliminarlo"
        type: "string"
        required: true    
      responses:
        "200":
          description: "Producto eliminado Correctamente"
        "400":
          description: "Error al eliminar producto"
        "401":
          description: "Token Invalido"
        "500":
          description : "Error"

  /v1/pedidos:
  
    get:
      tags:
        - "Pedidos"
      summary: "Trae listado de Pedidos"
      description: "Trae el listado de todos los Pedidos"
      operationId: "traerPedidos"
      consumes:
        - "aplication/json"
      parameters: 
      - in: query
        name: "pedido"
        type: "string"
        required: true
      - in: query
        name: "id_usuario"
        type: "string"
        required: true  
      responses:
        "200":
          description: "pedido encontrado"
          schema:
            type: "object"
            properties:
              id: 
                type: "number"
              id_usuario: 
                type: "number"
              total:
                type: "number"
              fecha: 
                type: "string"
              estado: 
                type: "string"
              fecha_estado: 
                type: "string"  
              productos: 
                type: "string"   
        "400":
          description: "La Operacion no existe"
        "401":
          description: "Token Invalido"
        "500":
          description : "Error"

    post:
      tags:
        - "Pedidos"
      summary: "Crear un Pedido"
      description: "Agrega una nuevo Pedido a la base de datos"
      operationId: "agregarPedido"
      consumes:
      - "aplication/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pedido creado"
        required: true
        schema:
          type: "object"
          properties:
            total: 
              type: "string"
            id_usuario:
              type: "string"
            estado: 
              type: "string"
            fecha_pedido:
              type: "string"
            fecha_estado:
              type: "string"
      responses:
        "200":
          description: "Pedido Creado Correctamente"
          schema:
            type: "object"
            properties:
              id_pedido: 
                type: "string"
              id_producto:
                type: "string"
              nombre_producto: 
                type: "string"
              cantidad: 
                type: "string"
              precio: 
                type: "string"
        "400":
          description: "Error al crear Pedido"
        "401":
          description: "Token Invalido"
        "500":
          description : "Error"
          
    put:
      tags:
        - "Pedidos"
      summary: "Editar un Pedido"
      description: "Edita un Pedido"
      operationId: "editarPedido"
      consumes:
        - "aplication/json"
      parameters:
        - name: "id"
          in : "body"
          description: "El Id del Pedido a Editar"
          required: true
          schema:
            type: "string"
        - in: query
          name: "estado"
          type: "string"
        - in: query
          name: "id_pedido"
          type: "string"
        - in: query
          name: "fecha_pedido"
          type: "string"
      responses:
        "200":
          description: "Pedido Editado Correctamente"
        "400":
          description: "Error al editar Pedido"
        "401":
          description: "Token Invalido"
        "500":
          description : "Error"
          
    delete:
      tags:
        - "Pedidos"
      summary: "Eliminar un Pedido"
      description: "Eliminar un Pedido"
      operationId: "eliminarPedido"
      parameters:
        - in: query
          name: "id_pedido"
          description: "El Id del pedido a Eliminar"
          type: "string"
          required: true
      responses:
        "200":
          description: "Pedido Eliminado Correctamente"
        "400":
          description: "Error al eliminar el Pedido"
        "401":
          description: "Token Invalido"
        "500":
          description : "Error"